apiVersion: v1
kind: Secret
metadata:
  name: ration-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:root1@postgres-service:5432/rationdb"
  JWT_SECRET: "your-secret-key"

  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root1
  VITE_API_URL: "http://api.ration"
  CORS_ORIGIN: "*"