services:
  postgres:
    image: postgres:16-alpine
    container_name: ration-postgres
    environment:
      POSTGRES_DB: rationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: ration-backend
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rationdb
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: my_super_secret_key
    ports:
      - "3000:3000"

  frontend:
    build: ./client
    container_name: ration-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"

volumes:
  postgres_data: